/* agecheck.obf.js — generated by obfuscate.js. Do not edit by hand. */
var _0x9d2 = ["push","from","base64","length","round"];
function _0x4a(_0xi) { return _0x9d2[(_0xi + 5 - 2) % 5]; }
var _0x1f = "wcLCwsLCsmRbW1tbW1ujZGhoaGhoaIjklpeXl5eXWxtbW1tbW1tpGw==";
var _0x5c = 91;
function _0xd(_0xb, _0xk) {
  var _0xr = [], _0xu = Buffer[_0x4a(3)](_0xb, _0x4a(4)); /* Buffer['from'](b,'base64') */
  for (var _0xi = 0; _0xi < _0xu[_0x4a(0)]; _0xi++) _0xu[_0xi] ^= _0xk;
  for (var _0xj = 0; _0xj + 8 <= _0xu[_0x4a(0)]; _0xj += 8) _0xr[_0x4a(2)](_0xu.readDoubleLE(_0xj));
  return _0xr;
}
var _0xW = _0xd(_0x1f, _0x5c);
var _0xf = new Function("f", "w",
  "return Math[" + JSON.stringify(_0x4a(1)) + "](w[4] + f.reduce(function(a,x,i){ return a + x*w[i]; }, 0));");
function _0xEst(_0xfeat) { return _0xf(_0xfeat, _0xW); }
(typeof module !== "undefined" ? module.exports : (self.AgeCheck = {})).estimateAge = _0xEst;
