/*
 * obfuscate.js — a real (if compact) obfuscation transform, so the RE target is
 * mechanically produced rather than hand-faked. It applies the layers a tool like
 * javascript-obfuscator would: (1) the model weights are packed to bytes, XORed
 * with a key and base64'd into a blob; (2) the formula tokens live in a rotated
 * string array behind an indirection function; (3) the predict body is assembled
 * at runtime via `new Function`; (4) identifiers are mangled to _0x hex names.
 *
 * Run:  node poc/obfuscated/obfuscate.js   (writes agecheck.obf.js)
 *
 * This is authored here rather than pulled from npm so the repo has no build
 * dependency; production obfuscators additionally do control-flow flattening,
 * which the dynamic recovery in deobfuscate.js defeats regardless.
 */
const fs = require("fs");
const path = require("path");

const WEIGHTS = [0.8, 1.5, -0.3, 2.1];
const BIAS = 18.0;
const XOR_KEY = 0x5b;

// Layer 1: weights+bias -> f64 bytes -> XOR -> base64 blob.
const params = WEIGHTS.concat([BIAS]);
const buf = Buffer.alloc(params.length * 8);
params.forEach((v, i) => buf.writeDoubleLE(v, i * 8));
const xored = Buffer.from(buf.map((b) => b ^ XOR_KEY));
const BLOB = xored.toString("base64");

// Layer 2: a rotated string array behind a decoder (classic obfuscator shape).
const rawStrings = ["length", "round", "push", "from", "base64"];
const ROT = 2;
const arr = rawStrings.slice(ROT).concat(rawStrings.slice(0, ROT)); // rotate left
const strArrayLiteral = JSON.stringify(arr);

// Layer 3+4: mangled names, blob decoder, and the predict body via new Function.
const obf = `/* agecheck.obf.js — generated by obfuscate.js. Do not edit by hand. */
var _0x9d2 = ${strArrayLiteral};
function _0x4a(_0xi) { return _0x9d2[(_0xi + ${arr.length} - ${ROT}) % ${arr.length}]; }
var _0x1f = "${BLOB}";
var _0x5c = ${XOR_KEY};
function _0xd(_0xb, _0xk) {
  var _0xr = [], _0xu = Buffer[_0x4a(3)](_0xb, _0x4a(4)); /* Buffer['from'](b,'base64') */
  for (var _0xi = 0; _0xi < _0xu[_0x4a(0)]; _0xi++) _0xu[_0xi] ^= _0xk;
  for (var _0xj = 0; _0xj + 8 <= _0xu[_0x4a(0)]; _0xj += 8) _0xr[_0x4a(2)](_0xu.readDoubleLE(_0xj));
  return _0xr;
}
var _0xW = _0xd(_0x1f, _0x5c);
var _0xf = new Function("f", "w",
  "return Math[" + JSON.stringify(_0x4a(1)) + "](w[4] + f.reduce(function(a,x,i){ return a + x*w[i]; }, 0));");
function _0xEst(_0xfeat) { return _0xf(_0xfeat, _0xW); }
(typeof module !== "undefined" ? module.exports : (self.AgeCheck = {})).estimateAge = _0xEst;
`;

const outPath = path.join(__dirname, "agecheck.obf.js");
fs.writeFileSync(outPath, obf);
console.log("wrote", outPath);
console.log("blob (XOR+base64):", BLOB);
